# ---

# default:
#   cache:
#     # TODO:
#     key: tst
#     paths:
#       - /usr/lib/python3.10/

variables:
  INIT_ENVIRONMENT: "apt-get update && apt-get install build-essential -y && source .venv/bin/activate"

stages:
  - init
  - lint
  # - format
  # - test

init:
  stage: init
  image: snakepacker/python:all
  before_script:
    - apt install python3.10-dev -y
    - python3.10 -m pip install poetry
  script:
    - poetry export -f requirements.txt --output requirements.txt --without-hashes
    - python3.10 -m venv .venv
    - source .venv/bin/activate
    - python -m pip install --no-cache-dir --upgrade -r requirements.txt
  artifacts:
      paths:
        - .venv

lint:
  stage: lint
  image: snakepacker/python:3.10
  dependencies:
    - init
  before_script:
    - bash -c $INIT_ENVIRONMENT
  script:
    - make lint

# # format:
# #   stage: format
# #   image: snakepacker/python:3.10
# #   # dependencies:
# #     # - init
# #   script:
# #     - make format

# # test:
# #   stage: test
# #   image: snakepacker/python:3.10
# #   # dependencies:
# #     # - init
# #   script:
# #     - make test
