# ---

# default:
#   cache:
#     # TODO:
#     key: tst
#     paths:
#       - /usr/lib/python3.10/

stages:
  - init
  - format
  - lint
  # - test

init:
  stage: init
  image: snakepacker/python:all
  before_script:
    - apt install python3.10-dev -y
    - python3.10 -m pip install poetry
  script:
    - poetry export -f requirements.txt --output requirements.txt --without-hashes
    - python3.10 -m venv .venv
    - source .venv/bin/activate
    - python -m pip install --no-cache-dir --upgrade -r requirements.txt
  artifacts:
      paths:
        - .venv
      expire_in: 30 minutes

format:
  stage: format
  image: alpine:3.18.3
  needs:
    - init
  before_script:
    - apt update
    - apt install build-essential -y
    - source .venv/bin/activate
  script:
    - make format

lint:
  stage: lint
  image: snakepacker/python:3.10
  needs:
    - init
    - format
  before_script:
    - apt update
    - apt install build-essential -y
    - source .venv/bin/activate
  script:
    - make lint

# # test:
# #   stage: test
# #   image: snakepacker/python:3.10
# #   # dependencies:
# #     # - init
# #   script:
# #     - make test
