---

default:
  cache:
    # TODO:
    key: tst
    paths:
      - /usr/lib/python3.10/

stages:
  - init
  - lint
  - format
  - test

# init:
#   stage: init
#   image: snakepacker/python:all
#   script:
#     - python3.10 -m pip install poetry
#     - poetry export -f requirements.txt --output requirements.txt --without-hashes
#     - python3.10 -m pip install --no-cache-dir --upgrade -r requirements.txt

lint:
  stage: lint
  image: snakepacker/python:3.10
  # dependencies:
    # - init
  before_script:
    - apt-get install build-essential
  script:
    - make lint

format:
  stage: format
  image: snakepacker/python:3.10
  # dependencies:
    # - init
  script:
    - make format

test:
  stage: test
  image: snakepacker/python:3.10
  # dependencies:
    # - init
  script:
    - make test
