version: '3.7'

services:
  app:
    build:
      context: .
    container_name: fastapi_app
    env_file:
      - ./.env
    command: "uvicorn app.main:app --reload --host ${APP_HOST} --port ${APP_PORT}"
    expose:
      - "${APP_PORT}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
