version: '3.7'

services:
  db:
    image: postgres:13.3
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    build:
      context: .
    container_name: fastapi_app
    env_file:
      - ./.env
    command: "uvicorn app.main:app --reload --host ${APP_HOST} --port ${APP_PORT}"
    expose:
      - "${APP_PORT}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
