openapi: 3.0.1

info:
  title: Book Library
  version: '1.0'

paths:
  /v1/genres:
    post:
      summary: Создание жанра
      tags:
        - genres
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenreCreateRequestV1'
        required: true
      responses:
        200:
          description: Жанр создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenreCreateResponseV1'
        409:
          description: Жанр с таким именем уже есть
    get:
      summary: Получение списка жанров
      tags:
        - genres
      parameters:
        - name: page
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Page'
        - name: size
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Size'
      responses:
        200:
          description: Список жанров
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenreGetListResponseV1'
  /v1/genres/{genre_id}:
    get:
      summary: Получение жанра
      tags:
        - genres
      parameters:
        - name: genre_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Детальная информация жанра
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenreGetDetailsResponseV1'
        404:
          description: Жанр не найден

components:
  schemas:

    # Common
    Page:
      description: Номер страницы результата
      type: integer
      minimum: 0
      default: 0

    Size:
      description: Размер страницы результата
      type: integer
      minimum: 0
      default: 10

    # Genres
    GenreId:
      description: Идентификатор жанра
      type: integer
      example: 1

    GenreName:
      description: Наименование жанра
      type: string
      example: Боевик

    GenreDetails:
      description: Детальная информация о жанре
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/GenreId'
        name:
          $ref: '#/components/schemas/GenreName'
      required:
        - id
        - name

    GenreBase:
      description: Базовая информация о жанре
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/GenreId'
        name:
          $ref: '#/components/schemas/GenreName'
      required:
        - id
        - name

    GenreCreateOrUpdate:
      description: Модель создания/редкатирования жанра
      type: object
      additionalProperties: false
      properties:
        name:
          $ref: '#/components/schemas/GenreName'
      required:
        - name

    GenreCreateRequestV1:
      $ref: '#/components/schemas/GenreCreateOrUpdate'

    GenreCreateResponseV1:
      $ref: '#/components/schemas/GenreDetails'
      
    GenreGetListResponseV1:
      type: object
      additionalProperties: false
      properties:
        genres:
          type: array
          items:
            $ref: '#/components/schemas/GenreBase'
        page:
          $ref: '#/components/schemas/Page'
        size:
          $ref: '#/components/schemas/Size'
      required:
        - genres
        - page
        - size

    GenreGetDetailsResponseV1:
      $ref: '#/components/schemas/GenreDetails'
      