"""empty message

Revision ID: f3ba3e4eb0cd
Revises: 4a3d41e94684
Create Date: 2023-09-12 19:29:03.617673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3ba3e4eb0cd'
down_revision: Union[str, None] = '4a3d41e94684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'publisher',
        sa.Column('name', sa.TEXT(), nullable=False),
        sa.Column('publisher_address', sa.TEXT(), nullable=True),
        sa.Column('publisher_website', sa.TEXT(), nullable=True),
        sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            'dt_created',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column(
            'dt_updated',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__publisher')),
        sa.UniqueConstraint('name', name=op.f('uq__publisher__name')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publisher')
    # ### end Alembic commands ###
